=== Dean4iq/something/src/main/resources/news/news.xsd
<?xml version="1.0"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="https://den-edu.herokuapp.com/">
    <element name="news">
        <complexType>
            <sequence>
                <element name="article" maxOccurs="unbounded" minOccurs="0">
                    <complexType>
                        <sequence>
                            <element name="header" type="string"/>
                            <element name="description" type="string"/>
                            <element name="text" type="string"/>
                            <element name="to_be_displayed" type="date" minOccurs="0"/>
                            <element name="published" type="dateTime"/>
                        </sequence>
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>
</schema>

=== Dean4iq/something/src/main/resources/news/news_uk.xml
<?xml version="1.0" encoding="UTF-8"?>
<news:news xmlns:news="https://den-edu.herokuapp.com/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="https://den-edu.herokuapp.com/ news.xsd">
    <article>
        <header>Оновлення сервісу</header>
        <description>Можливість використання сервісу для українських слів</description>
        <text>З 22 вересня на сервері з'явилася можливість використання сервісу з українськими текстами</text>
        <to_be_displayed>2019-09-22T09:00:00</to_be_displayed>
        <published>2019-09-21T10:00:00</published>
    </article>
    <article>
        <header>Технічні роботи</header>
        <description>Проведення робіт 1 березня 2019 (09:00 - 11:00)</description>
        <text>1 березня 2019 з 9 до 11 ранку будуть проводитися технічні роботи, у зв'язку з чим сервіс буде недоступним</text>
        <published>2019-02-28T12:33:11</published>
    </article>
</news:news>
